<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Business Analytics</title>
  <meta name="description" content="Business Analytics" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Business Analytics" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Business Analytics" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">BA</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#linear-programming"><i class="fa fa-check"></i><b>1</b> Linear Programming</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#production-planning"><i class="fa fa-check"></i><b>1.2</b> Production Planning</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#transportation-problem"><i class="fa fa-check"></i><b>1.3</b> Transportation problem</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Business Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Business Analytics</h1>
</div>
<div id="linear-programming" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Linear Programming</h1>
<p>This chapter is primarily based on
Hillier-Liebermann (2001): Introduction to Operations Research.</p>
<p><a href="./Code/14-lp.R">You can download the corresponding R-Code here</a></p>
<div id="introduction" class="section level2" number="1.1">
<h2><span class="header-section-number">1.1</span> Introduction</h2>
<p>Linear programming is a problem-solving approach that has been developed to help managers make decisions. It uses a mathematical model to describe the problem of concern. The adjective linear means that all the mathematical functions in this model are required to be linear functions. The word programming does not refer here to computer programming; rather, it is essentially a synonym for planning. Thus, linear programming involves the planning of activities to obtain an optimal result that maximizes or minimizes the outcome.</p>
<p>In general, the process of Linear Programming follows three steps:</p>
<ul>
<li><p>The process begins by carefully observing and formulating the problem, including gathering all relevant data.</p></li>
<li><p>The next step is to construct a mathematical model that attempts to abstract the real problem.</p></li>
<li><p>It then attempts to find an optimal solution.</p></li>
</ul>
<p>Optimization models are used to make the optimum decision concerning the design of a system by allocating scarce resources.</p>
<ul>
<li><p><strong>Production Planning</strong>: Given several products with varying production requirements and cost structures, determine how much of each product to produce in order to maximize profits.</p></li>
<li><p><strong>Scheduling</strong>: Given a staff of people, determine an optimal work schedule that maximizes worker preferences while adhering to scheduling rules.</p></li>
<li><p><strong>Network Installation</strong>: Given point-to-point demands on a network, install capacities on the telecom links so as to minimize installation and routing costs.</p></li>
</ul>
<p>The three main components of an optimization model are:</p>
<ul>
<li><p><strong>Objective function</strong>: a function to be minimized or maximized</p></li>
<li><p><strong>Decision variables</strong>: controllable variables that influence the result of the objective function</p></li>
<li><p><strong>Constraints</strong>: restrictions for the values the decision variables can take</p></li>
</ul>
<p>When all decision variables and constraints in the model are linear, linear programming is used to solve an optimization problem.
In R, the package <code>lpSolve</code> is used for solving linear programming problems.</p>
</div>
<div id="production-planning" class="section level2" number="1.2">
<h2><span class="header-section-number">1.2</span> Production Planning</h2>
<p>Consider the following example on how to solve linear programs in R.</p>
<blockquote>
<p>A company wants to determine how much of each product 1 and 2 to produce in order to maximize profits. They have three plants with limited capacities. Product 1 requires 1 hour at plant 1 and 3 hours at plant 3, generating profits of $3 per item. Product 2 requires 2 hours at plant 2 and 3 hours at plant 3, and can be sold for $5 per item. The production capacities are 4, 12, and 18 hours, for plant 1, 2, and 3, respectively. Because both products are competing for the same production capacity in Plant 3, it is not clear which mix of the two products is most profitable.
We want to determine how many items of each of the two products should be produced in order to maximize the total profit, subject to the restrictions imposed by the limited production capacities available in the three plants.</p>
</blockquote>
<p>The corresponding mathematical model will then be defined as follows:</p>
<p><span class="math inline">\(x_1\)</span>: number of produced items of product 1</p>
<p><span class="math inline">\(x_2\)</span>: number of produced items of product 2</p>
<p><span class="math display">\[
\begin{aligned}
max.\ 3x_1 * 5x_2 \\
s.t. \\
3x_1 \leq 4 \\
2x_2 \leq 12 \\
3x_1 + 2x_2 \leq 18 \\
x_1 \geq 0 \\
x_2 \geq 0
\end{aligned}
\]</span></p>
<p>To solve this linear programming model in R, we first need to import the lpSolve package. Do not forget to install the package first, if not already installed.</p>
<p>To build the model, first the coefficients f the objective function need to be set:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>objective<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">5</span>)</span></code></pre></div>
<p>The production capacity constraints of the linear programming model shown above can be summarized in the following matrix:
<span class="math display">\[
\begin{bmatrix}
3 &amp; 0\\
0 &amp; 2\\
3 &amp; 2
\end{bmatrix}
\begin{bmatrix}
x_1\\
x_2
\end{bmatrix}
\leq
\begin{bmatrix}
4\\
12\\
18
\end{bmatrix}
\]</span></p>
<p>The non-negativity constraint can be ignored, R automatically assumes this constraint.
The constraints are constructed with three different functions. First, the left-hand side:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>constraint.lhs <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">2</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The argument <code>nrow=3</code> ensures that the matrix has three rows. The argument <code>byrow=TRUE</code> causes the numbers 3,0,0,2,3,2 to be arranged line by line in the generated matrix.</p>
<p>Next, the inequality signs are set:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>constraint.direction <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;&lt;=&quot;</span>,<span class="st">&quot;&lt;=&quot;</span>,<span class="st">&quot;&lt;=&quot;</span>)</span></code></pre></div>
<p>Finally, the right hand side of the constraints are set:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>constraint.rhs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">12</span>,<span class="dv">18</span>)</span></code></pre></div>
<p>To run the optimization, the function <code>lp</code> is used.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lp</span>(<span class="at">direction=</span><span class="st">&quot;max&quot;</span>, objective, constraint.lhs, constraint.direction, constraint.rhs)</span></code></pre></div>
<pre><code>## Success: the objective function is 34</code></pre>
<p>Here, we get a success message and the objective value of $34 is returned.</p>
<p>The final values of the decision variables are displayed using this function and adding <code>$solution</code>.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># display final values</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lp</span>(<span class="at">direction=</span><span class="st">&quot;max&quot;</span>, objective, constraint.lhs, constraint.direction, </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>   constraint.rhs)<span class="sc">$</span>solution</span></code></pre></div>
<pre><code>## [1] 1.333333 6.000000</code></pre>
<p>So, we should order 1.33 items of product 1 and 6 items of product 2.</p>
<p>Adding <code>$duals</code> shows the shadow prices for the constraints as well as for the decision variables.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># display shadow prices and decision variables</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lp</span>(<span class="st">&quot;max&quot;</span>, objective, constraint.lhs, constraint.direction, </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>   constraint.rhs, <span class="at">compute.sens=</span><span class="cn">TRUE</span>)<span class="sc">$</span>duals</span></code></pre></div>
<pre><code>## [1] 1.0 2.5 0.0 0.0 0.0</code></pre>
</div>
<div id="transportation-problem" class="section level2" number="1.3">
<h2><span class="header-section-number">1.3</span> Transportation problem</h2>
<p>A transportation problem is a special form of linear programming. Here, the goal is to minimize transportation cost or distance to transport a given commodity from a number of origins to a number of destinations. The constraints are given as capacities of the origins and demand of the destinations.</p>
<p>A common notation of transportation problems is:</p>
<p>m = number of sources (1…m)</p>
<p>n = number of destinations (1…n)</p>
<p><span class="math inline">\(c_{ij}\)</span> = unit cost of shipping one unit from source i to destination j</p>
<p><span class="math inline">\(x_{ij}\)</span>= amount shipped from source i to destination j</p>
<p><span class="math inline">\(s_i\)</span> = supply (capacity) at source i</p>
<p><span class="math inline">\(s_i\)</span> = demand at destination j</p>
<p>Let’s illustrate that based on an example of a classical transportation problem. Consider a regional retail company selling organic apples. They purchase their apples at three farms or suppliers from the region. They sell the apples to four customers who process them then to organic apple juice. However, the customers and suppliers are distributed throughout the region. The company must decide now which customer should be supplied by which supplier. Here, they have to consider the transportation costs to deliver the apples from the supplier to the customer.</p>
<p>The table provides the amount of apples each supplier can provide and the amount of apples each customer demands. The gray cells show the transportation costs for each supplier-customer combination.</p>
<table>
<thead>
<tr class="header">
<th>Cost</th>
<th align="center">Customer 1</th>
<th align="center">Customer 2</th>
<th align="center">Customer 3</th>
<th align="center">Customer 4</th>
<th align="center">Supply</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Supplier 1</strong></td>
<td align="center">10</td>
<td align="center">2</td>
<td align="center">20</td>
<td align="center">11</td>
<td align="center"><strong>15</strong></td>
</tr>
<tr class="even">
<td><strong>Supplier 2</strong></td>
<td align="center">12</td>
<td align="center">7</td>
<td align="center">9</td>
<td align="center">20</td>
<td align="center"><strong>25</strong></td>
</tr>
<tr class="odd">
<td><strong>Supplier 3</strong></td>
<td align="center">4</td>
<td align="center">14</td>
<td align="center">16</td>
<td align="center">18</td>
<td align="center"><strong>10</strong></td>
</tr>
<tr class="even">
<td><strong>Demand</strong></td>
<td align="center"><strong>5</strong></td>
<td align="center"><strong>15</strong></td>
<td align="center"><strong>15</strong></td>
<td align="center"><strong>15</strong></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<p>In mathematical form, this transportation problem looks like this:
<span class="math display">\[
\begin{aligned}
min.\ \sum_{i=1}^{3} \sum_{j=1}^{4} c_{ij}x_{ij} \\
s.t. \\
x_{11}+x_{12}+x_{13}+x_{14} \leq 15 \\
x_{21}+x_{22}+x_{23}+x_{24} \leq 25 \\
x_{31}+x_{32}+x_{33}+x_{34} \leq 10 \\
x_{11}+x_{21}+x_{31} \geq 5 \\
x_{12}+x_{22}+x_{32} \geq 15 \\
x_{13}+x_{23}+x_{33} \geq 15 \\
x_{14}+x_{24}+x_{34} \geq 15 \\
x_{ij} \geq 0
\end{aligned}
\]</span></p>
<p>The R code to solve this transportation problem then looks as follows. First, we define the cost matrix in R.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>costs<span class="ot">&lt;-</span><span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">2</span>,<span class="dv">20</span>,<span class="dv">11</span>,<span class="dv">12</span>,<span class="dv">7</span>,<span class="dv">9</span>,<span class="dv">20</span>,<span class="dv">4</span>,<span class="dv">14</span>,<span class="dv">16</span>,<span class="dv">18</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Then we specify the customers´and the suppliers´ names. They are added as column names and rownames of the cost matrix, for customers and suppliers, respectively.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(costs) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Customer 1&quot;</span>, <span class="st">&quot;Customer 2&quot;</span>, <span class="st">&quot;Customer 3&quot;</span>, <span class="st">&quot;Customer 4&quot;</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(costs) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Supplier 1&quot;</span>, <span class="st">&quot;Supplier 2&quot;</span>, <span class="st">&quot;Supplier 3&quot;</span>)</span></code></pre></div>
<p>The transportation problem consists out of two sets of constraints. One set specifying the maximum capacity at the supplier and the other one the minimum demand required by the customers.</p>
<p>The supplier constraints are built with smaller or equal signs. As the suppliers are considered the rows in the matrix above, we use the following formula to set the inequality signs and right hand side coefficients:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>row.signs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">&quot;&lt;=&quot;</span>, <span class="dv">3</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>row.rhs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">25</span>, <span class="dv">10</span>)</span></code></pre></div>
<p>The customer constraints are built with larger or equal signs. As the customers are considered the columns in the matrix above, we use the following formula to set the inequality signs and right hand side coefficients:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>col.signs <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">&quot;&gt;=&quot;</span>, <span class="dv">4</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>col.rhs <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">15</span>, <span class="dv">15</span>, <span class="dv">15</span>)</span></code></pre></div>
<p>The final values are retrieved as in the simple linear program shown above.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lp.transport</span>(costs, <span class="st">&quot;min&quot;</span>, row.signs, row.rhs, col.signs, col.rhs)</span></code></pre></div>
<pre><code>## Success: the objective function is 435</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lp.transport</span>(costs, <span class="st">&quot;min&quot;</span>, row.signs, row.rhs, col.signs, col.rhs)<span class="sc">$</span>solution</span></code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    0    5    0   10
## [2,]    0   10   15    0
## [3,]    5    0    0    5</code></pre>
<p>The total transportation costs for this problem are $435. The allocation is shown in the table below.</p>
<table>
<thead>
<tr class="header">
<th>Allocation</th>
<th align="center">Customer 1</th>
<th align="center">Customer 2</th>
<th align="center">Customer 3</th>
<th align="center">Customer 4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Supplier 1</strong></td>
<td align="center">-</td>
<td align="center">5</td>
<td align="center">-</td>
<td align="center">10</td>
</tr>
<tr class="even">
<td><strong>Supplier 2</strong></td>
<td align="center">-</td>
<td align="center">10</td>
<td align="center">15</td>
<td align="center">-</td>
</tr>
<tr class="odd">
<td><strong>Supplier 3</strong></td>
<td align="center">5</td>
<td align="center">-</td>
<td align="center">-</td>
<td align="center">5</td>
</tr>
</tbody>
</table>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"search": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
